### PR TITLE
Move to YAML format

### PR DESCRIPTION
**Pull request by codeallthethingz**
The custom CSV format is problematic because

1. It requires you to write a custom parser which is error prone and slow.
2. It requires you to reimplement this custom parser in any language or project that needs to parse these input files.
3. It's not extendable for new data structures that may be added in the future.
4.  (opinion) The csv data files are not as human readable.

The yaml schema in the new files matches the data structure required by main.js reader and reduced lines of code by ~30.

Downsides:
It does increase the verbosity of the data files.

New format:

```yaml
---
name: Object A
width: 20
height: 20 
features: 
  - { x: 3, y: 3, data: A }
  - { x: 3, y: 4, data: A }
  - { x: 3, y: 5, data: A }
  - { x: 4, y: 3, data: A }
  - { x: 4, y: 4, data: A }
  - { x: 4, y: 5, data: A }
  - { x: 5, y: 3, data: A }
  - { x: 5, y: 4, data: A }
  - { x: 5, y: 5, data: A }
  - { x: 12, y: 7, data: B }
  - { x: 12, y: 8, data: B }
  - { x: 12, y: 9, data: B }
  - { x: 13, y: 7, data: B }
  - { x: 13, y: 8, data: B }
  - { x: 13, y: 9, data: B }
  - { x: 14, y: 7, data: B }
  - { x: 14, y: 8, data: B }
  - { x: 14, y: 9, data: B } 
```

Testing:  Still renders - 

image

### CODE REVIEW

**Comment by rhyolight** [comment]
Don't forget to `git add static/bower_components/js-yaml/dist/js-yaml.js`

**Review by rhyolight — CHANGES_REQUESTED** [review]
Don't forget to `git add static/bower_components/js-yaml/dist/js-yaml.js`.

**Comment by codeallthethingz** [comment]
Ah, `static/bower_components/` was in the gitignore so it didn't get picked up.  I'll remove that and add the files.

**Comment by codeallthethingz** [comment]
@rhyolight fixed.

**Review by rhyolight — CHANGES_REQUESTED** [review]
I don't see a change to `package.json`, but you added `js-yaml` as a dependency. Shouldn't you run `npm install js-yaml --save`?

**Comment by codeallthethingz** [comment]
Oh I used bower as that's what the format seemed to be. Your dependencies aren't in the package json. Feel free to merge and modify

**Review by rhyolight — APPROVED** [review]

**Pull request merged**
